baseURL = 'https://ayyzenn.github.io/'
languageCode = 'en-us'
title = 'ayyzenn'

theme = 'hugo-PaperMod'


[params.profileMode]
    enabled = true
    title = "Saad Ahmad"
    subtitle = "The First Thinker!"
#    imageUrl = "https://raw.githubusercontent.com/hissamshar/hissamshar.github.io/refs/heads/master/Cropped_Image.png"
    imageTitle = "Profile Picture"
    imageWidth = 200
    imageHeight = 200

[[params.profileMode.buttons]]
    name = "About Me"
    url = "/about"
    #weight = 1

[[params.profileMode.buttons]]
    name = "Archives"
    url = "/archives"
  


# And you can even create generic menu

[[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 300
    url = "/tags/"


[[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
  name = "Search"
  url = "/search"


[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"
    ShowToc =  true
    ShowReadingTime = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    taglist = true
    defaultTheme = 'dark'

